### PR TITLE
Set the jre8 version as default

### PR DESCRIPTION
**Pull request by gstojsic**
this is in relation to issue #59

### CODE REVIEW

**Comment by v-xiangs** [comment]
@gstojsic thank you very much for the great idea to have a default build. our team likes your idea a lot. just one suggestion, instead of moving profile `build42` to the <build> section, can we just add <activeByDefault> to the profile `build42` to make it default? thanks.

**Comment by gstojsic** [comment]
Of course you could make the `build42` the active profile. In fact that was my first solution but then I decided for the submitted one because it requires less code (the xml stuff is already very noisy). This reduced the pom by 9 lines and the other solution would increase the noise and add several lines. Secondly, it is clearer for beginners to understand (you need not care about maven profiles if you are not interested in jre7 stuff to make sense of the pom). Also I believe that the solution I submitted is closer to the way maven builds were intended to work - try to use defaults as much as possible and specify overrides only when needed. Anyway, feel free to amend the pom as you see fit. Having the `build42` set as the active profile would also be a step forward IMHO.

**Comment by v-xiangs** [comment]
@gstojsic thank you for your valuable thought. after talking to the team, we decided to keep 2 profiles because we think using profiles is better for maintenance when new JDK comes out.
However, it is a great idea to make jre8 the default profile. Do you mind to help us adding '<activeByDefault>' to 'build42' profile and keep anything else the same as it is? thank you.

**Comment by gstojsic** [comment]
There you go. Thanks for considering the idea.

**Comment by v-xiangs** [comment]
@gstojsic thank you for your contribution. We really appreciate all your ideas and fixes.

**Pull request merged**
