### PR TITLE
Fix SqlAuthenticationToken constructor accepting unix epoch

### PR DESCRIPTION
**Pull request by konjac**
This is to address #2424

### CODE REVIEW

**Comment by konjac** [comment]
@barryw-mssql @tkyc Could you help to review this fix?

**Review by barryw-mssql — APPROVED** [review]

**Comment by Jeffery-Wasty** [comment]
@konjac Thanks for the PR, we'll take a look at it and get back to you with our thoughts.

**Comment by Jeffery-Wasty** [comment]
It looks like this is an issue of the documentation being wrong, not the implementation. When creating the `SQLAuthenticationToken` we are indeed passing in millisecond values, but the Javadoc should be changed to reflect that.

**Review by tkyc — APPROVED** [review]

**Review by Jeffery-Wasty — CHANGES_REQUESTED** [review]
Hold off on merging for a bit

**Review by tkyc — DISMISSED** [review]

**Review by Jeffery-Wasty — APPROVED** [review]

**Review by barryw-mssql — APPROVED** [review]

**Pull request merged**
