### PR TITLE
Add | Allow use of platform gss for kerberos authentication

### PR DESCRIPTION
**Pull request by fogerd**

### CODE REVIEW

**Comment by v-zhangw** [comment]
Hello @fogerd,

Are you still working on this PR? If so could you resolve the conflicts and provide a description of the functionality?


In addition is this implementation not missing logic to account for different subject usages?

**Comment by v-zhangw** [comment]
Hello @fogerd,

Are you still working on this PR? If so could you resolve the conflicts and provide a description of the functionality?


In addition is this implementation not missing logic to account for different subject usages?

**Comment by lilgreenbird** [comment]
#1806

**Comment by tkyc** [comment]
Closing as the driver already supports native GSS. Refer to this wiki link https://github.com/microsoft/mssql-jdbc/wiki/Native-platform-GSS-Integration

**Pull request closed without merging**
