### PR TITLE
Use Socket instead of SocketChannel when multiSubnetFailover=true

### PR DESCRIPTION
**Pull request by ulvii**
Fix for both #144 and #645 .This PR reverts #160.

Switching from SocketChannels to Sockets to avoid creating 2 connections when multiSubnetFailover=true.

### CODE REVIEW

**Comment by ulvii** [comment]
Attaching the jars: [PR662_jars.zip](https://github.com/Microsoft/mssql-jdbc/files/1831182/6.5.1-SNAPSHOT_jars.zip)

**Comment by greg-pendlebury** [comment]
Thanks @ulvii, one of our DBAs tested the jar with JMeter using the same test we used in demonstrating #645. He has confirmed that the NUMA affinity issues are resolved. We will try updating our full application once a release of the driver is available, but the regression testing of all the other changes since 6.1.7 might take us some time.

**Comment by sehrope** [comment]
Sure we'll get this tested. Are the jars you've attached built off the tip of this PR? i.e. can I just build the PR?

I took a peek at the diff itself and it's quite minimal. The main change seems to be replacing `findSocketUsingJavaNIO(...)` with `findSocketUsingThreading(...)` which has existed at least since the open sourcing of the driver but doesn't seem to have been referenced in any active code.

**Comment by ulvii** [comment]
Thanks @greg-pendlebury , @sehrope .

@sehrope , yes the jars are built on top of the PR.

**Comment by sehrope** [comment]
We tested this a bit and it doesn't break query cancellation when multiSubnetFailover is enabled.

I think it'd be worthwhile to eventually rewrite how `SocketFinder` is implemented. The concept itself is fine, i.e use a thread pool to race opening sockets to all resolved addresses. The complexity is that it's done using manual locking, `.wait(...)`, `.notify()` and the code is intermixed with the parent class. It likely predates modern concurrency primitives and redoing it using something like Future or CountDownLatch would simplify things.

The current code also handles IPv4 and IPv6 sequentially. I don't see that behavior explicitly documented anywhere nor does it seem like it'd be useful. If a user has multiple address types resolving from a host name they should all be attempted in parallel right? I took a stab at a high level clean up for this. See here for a PR: #663

**Pull request merged**
