### PR TITLE
Upgrade osgi jdbc add tck

### PR DESCRIPTION
**Pull request by laeubi**
This includes:
- https://github.com/microsoft/mssql-jdbc/pull/2064
- https://github.com/microsoft/mssql-jdbc/pull/2065

### CODE REVIEW

**Comment by laeubi** [comment]
@Jeffery-Wasty I don't really understand how to get more details about the testfailure can you give me a hint?

**Comment by Jeffery-Wasty** [comment]
@laeubi, we'll have to look into this. Previously the errors were caused by `eclipse.osgi` dependency, but now I'm not seeing that in our tests, I'll get back to you with more information. Regardless, we'll look at the upgrade to `osgi.service` and the new properties and see if we can get that merged first, those two changes look fine. Thank you for your work on this.

**Comment by Jeffery-Wasty** [comment]
Can you please confirm for us the necessity and use of the test? Is implementation of this test required by spec, or is this just a confirmation that the properties have been added correctly. It looks like the issues are all caused by the added test, so if it can be omitted, that would help us.

**Comment by laeubi** [comment]
It is not strictly required, this just ensures that the implementation is fulfilling the spec.
So if it can even be omitted, it would still be interesting *why* this fails (I can't really get an idea from the checks output), and I was not able to run the tests locally.

**Comment by Jeffery-Wasty** [comment]
Thanks for the explanation. We're still looking into it, its not readily apparent from the logs why this is failing, but we'll keep you updated on progress regarding this pr.

**Review by lilgreenbird — COMMENTED** [review]
Why are there multiple PRs on this? Does this obsolete #2064 and #2065 if so please close those PRs. Can you please add some details and references to why this change is necessary.

**Comment by Jeffery-Wasty** [comment]
Hi @laeubi,

The issue is that the test is that its using Junit5, and when this is invoked, causes issues in other tests in the project. If the tests can be rewritten only using features of Junit4 or below, that will allow it to pass and be included as part of the changes.

Comparing the test styles from this PR and #2017, I think the one in 2017 fits the project better, as opposed to the additional test information in the pom. Let's move forward with 2017 being the only PR for this change. We'll close the others, but thank you for this layered approach, it really helped in narrowing down on the problem.

**Pull request closed without merging**
