### PR TITLE
Adding Delayed Durability

### PR DESCRIPTION
**Pull request by dbrownems**
Adding an overload of commit() to support delayed durability.  Fixed compilation error.  Didn't add method to ISQLServerConnection interface.  Not sure if that is desirable.

### CODE REVIEW

**Comment by peterbae** [comment]
Hi @dbrownems, thank you for your contribution. I think adding an option to enable delayed durability could be useful to some users. Could you modify the commit() method so that it calls the commit(false) method to remove some code duplication here?

**Comment by dbrownems** [comment]
Do you think it needs to be added to ISqlServerConnection and to the proxy type too?  Also I can't get the project to build.  Are there any better instructions?  I tried from the commandline and various IDEs, but no luck.

**Comment by peterbae** [comment]
We have instructions for building the JAR files using maven in our README file (let us know if you're stuck on one of the steps). This won't need to be added to ISqlServerConnection or the proxy type.

**Comment by ulvii** [comment]
Thanks for contribution @dbrownems

**Pull request merged**
