### PR TITLE
Make Ms Jdbc driver more spring friendly - dev

### PR DESCRIPTION
**Pull request by gstojsic**
This is in relation to issue: https://connect.microsoft.com/SQLServer/Feedback/Details/3100563
It would greatly simplify Tvp usage in the Spring environment.
Per you request the pull request is made from the dev branch.

### CODE REVIEW

**Comment by v-afrafi** [comment]
Thank you for your contribution! 
According to the sample you provided in this [link](https://connect.microsoft.com/SQLServer/Feedback/Details/3100563), you need to add setSqlType method to pass the TVP name. 
    inputDataTable.setSqlType("[dbo].[MsDriverSqlType]");
Could you make changes to the method names to be more meaningful?

**Comment by gstojsic** [comment]
@v-afrafi If I understood correctly you want me to rename the sqlType property I added to SQLServerDataTable. In the setStructured api from SQLServerPreparedStatement the parameter is named tvpName. Would that name be ok?

**Comment by v-afrafi** [comment]
sounds good, thanks!

**Comment by gstojsic** [comment]
Renamed sqlType to tvpName as requested.

**Pull request merged**
