### PR TITLE
TimeoutTimer to TimeoutPoller performance enhancement

### PR DESCRIPTION
**Pull request by shayaantx**
Modified the TimeoutTimer to not be a unlimited thread pool, instead its one thread that lets TDS commands register/deregister with it, when a timeout is configured, and that thread will timeout the command if necessary. Included test cases

See https://github.com/Microsoft/mssql-jdbc/issues/755 for more context

Please let me know of any necessary changes or requests, I'm not sure why git is showing all these white space changes, but in the git history in my ide it doesn't show...

### CODE REVIEW

**Comment by shayaantx** [comment]
no idea why my change would cause the sql2017 build to fail for below results, I'll run them later locally and look into it

[ERROR] Failures: 
[ERROR]   bvtTest.testTwoResultsetsDifferentStmt:374 Unexpected bigint value, expected: 5869790151273323877 .Retrieved: -1985958062194855290 ==> expected: <true> but was: <false>
[ERROR]   bvtTest.testTwoResultsetsSameStmt:409 Unexpected bigint value, expected: 5869790151273323877 .Retrieved: -1985958062194855290 ==> expected: <true> but was: <false>

**Comment by cheenamalhotra** [comment]
@shayaantx Yes, we are aware of the intermittent test failures, and have a fix coming soon with PR #762. Sorry for any inconvenience.

**Comment by cheenamalhotra** [comment]
Hi @shayaantx 

About whitespace changes, please make sure your code is formatted with [mssql-jdbc-formatter](https://github.com/Microsoft/mssql-jdbc/blob/dev/mssql-jdbc_formatter.xml).

**Comment by shayaantx** [comment]
@cheenamalhotra I fixed the white space changes, please let me know if anything else is necessary

**Comment by shayaantx** [comment]
@cheenamalhotra anything else required to get this submitted?

**Comment by ulvii** [comment]
Hi @shayaantx ,

The team will review the changes for the next release, please stay tuned.

**Comment by cheenamalhotra** [comment]
Hi @shayaantx 

Please merge PR [#1](https://github.com/shayaantx/mssql-jdbc/pull/1) in your forked repository so we can proceed with testing this PR in internal test lab thoroughly.

**Comment by shayaantx** [comment]
@cheenamalhotra done

Please let me know of any issues and I can address them

**Comment by cheenamalhotra** [comment]
Thanks @shayaantx for the quick turnaround!

We reviewed the Pull Request, and were wondering if you'd consider extending the implementation to [`BulkTimeoutTimer`](https://github.com/Microsoft/mssql-jdbc/blob/0a1759f7b95ab38f45dbefec370e0eadf4776e9d/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java#L253) as well. In this case, it would also be neater to maintain a separate Java class e.g. `TimeoutHandler` (or anything appropriate) for holding `TimeoutPoller` and `TimeoutCommand` classes instead of keeping them in `IOBuffer`.

**Comment by shayaantx** [comment]
@cheenamalhotra I've made the changes to use TimeoutPoller in the bulk copy mechanism.

I was looking at BulkCopyTimeoutTest#testZeroTimeOut and I don't think this test actually will work with my changes and I don't think it worked before my changes based on how I think it was initially designed.

The test bulk copy takes like 100ms locally, so a zero timeout, should trigger a timeout exception, however this test case is **not** designed to expect a exception thrown, so it doesn't actually validate a timeout is thrown.

I'd like to propose adding jmockit to pom.xml to include the library to easily mock parts of the bulk copy (without large refactoring) to make this test actually work (basically mock core parts of the bulk copy to introduce an actual way to timeout the copy, simulating the timeout).  Please let me know if you'd like to see an example in my fork and I'll put it up

**Comment by cheenamalhotra** [comment]
Thanks for the changes @shayaantx . Very much appreciated.

JMockit would be worth looking into, please feel free to setup a PR sometime that demonstrates your example, we'll review and take it from there and will try scaling it up if it proves useful :)

**Comment by ulvii** [comment]
Hi @shayaantx ,

Great work, we appreciate your efforts. 👍 

I took a quick look at the PR and wanted to mention a few things before the team proceeds with the detailed review. 

1. _The test bulk copy takes like 100ms locally, so a zero timeout, should trigger a timeout exception._
-Note that 0 timeout indicates no limit; the driver waits indefinitely to complete the bulk copy operation. See `BulkCopyTimeout` [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-bulk-copy-with-the-jdbc-driver?view=sql-server-2017#sqlserverbulkcopyoptions). **Do you still think JMockit is required?** 
2. I also noticed you added `-javaagent:${settings.localRepository}/org/jmockit/jmockit/${jmockit.version}/jmockit-${jmockit.version}.jar` to JVM arguments in pom.xml to get JMockit working. This means if someone wants to run the tests without using Maven, on Eclipse for example, they have to manually provide `javaagent` argument. I will wait for the team to decide on this. 
3. _I also moved TDSWriter/TDSCommand out of IOBuffer, I really wasn't sure if you guys/gals would approve such a change, but I need these classes accessible to do some mocking._
-TDSWriter/TDSCommand should not be exposed to applications, they should remain package-private. 
4. Please also apply the [formatter](https://github.com/Microsoft/mssql-jdbc/blob/dev/mssql-jdbc_formatter.xml) to your changes, remove unused imports, add license header to the new files. 
5. Please also remove ErrorConstants.java and directly use `R_queryTimedOut` and `R_connectionIsClosed`, to keep it consistent in the driver. 
5. _I noticed that if I timeout a bulk copy at certain times, the driver will correctly throw the timeout exception, however if we try to do anything else with the statement, sql server throws "Bulk load data was expected but not sent"._
-This should not really happen, statement has to be available even if bulk copy operation failed with an exception. I tried a few test cases, also BulkCopyTimeoutTest, but could not reproduce the issue. We recently merged a [PR](https://github.com/Microsoft/mssql-jdbc/pull/801) which was meant to fix the issues with bulk copy error handling. If you could provide me a simple repro code, I can take a look if it is an actual driver issue.

**Comment by shayaantx** [comment]
@ulvii 

Thanks for the response

1. That comment by me was invalid since a zero timeout like you mentioned doesn't trigger a timeout, Something like* jmockit is helpful for a test like testRealTimeout() where we want to test bulk copy functionality and the timeout functionality (since thats what I changed)

2. Yes, you would need to add that or we would need to confirm the junit tests differently. It is definitely possible to configure your junit runner/suite to not have this required, but I'd need to spend some time investigating it.

3. Yea I figured that wouldn't be ideal. If using the mocking framework is desired, then tests for package private classes would need to be in same package in the test src (so in this case this one bulk copy timeout test would need to be moved from com.microsoft.sqlserver.jdbc.bulkCopy to com.microsoft.sqlserver.jdbc.

4. I've been applying the formatter with eclipse, which file was missing the formatting?

5. Can do

6. Replace the below block of code in BulkCopyTestUtil#performBulkCopyWithoutErrorHandling (line#370)
`
		// we drop the destination table in a separate connection because we could of
		// timed out before sending
		// a batch so then any subsequent operations in sql server will result in an
		// error "Bulk load data was expected but not sent"
		dropDestinationTable(wrapper, destinationTable);`

with

`finally {
                if (dropDest && null != destinationTable) {
                    stmt.dropTable(destinationTable);
                }
            }`

**Comment by shayaantx** [comment]
If it is simpler I can go back to my changes before the jmockit pr, but someone on your end should confirm my changes are valid (I tested them and they seem fine). It's just weird for me to commit any code without some test case covering most of the edge cases

Please let me know what your preference is and I'll get it done

**Comment by cheenamalhotra** [comment]
Hi @shayaantx 

Please make changes as suggested by @ulvii above. The file changes are making difficult to review specific changes requested. For formatting code, please use [mssql-jdbc-formatter](https://github.com/Microsoft/mssql-jdbc/blob/dev/mssql-jdbc_formatter.xml) from this repository in eclipse.

Also, JMockit should not be part of this PR, another PR would be helpful if we need to add that to tests.

**Comment by shayaantx** [comment]
my fork turned into a mess during the revert, I'm going to just reimplement again in separate pull :|

**Pull request closed without merging**
