### PR TITLE
Fix | Negotiate NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY flag for NTLM authentication

### PR DESCRIPTION
**Pull request by ulvii**

### CODE REVIEW

**Comment by pcloud81** [comment]
can I check, when will this fix be released? Thanks.

**Comment by ulvii** [comment]
The next preview release is scheduled for mid December.

**Comment by pcloud81** [comment]
> The next preview release is scheduled for mid December.

When will it be under official release? Will there be a hotfix to v7.4.1?

**Comment by ulvii** [comment]
There is no exact date for the next official release yet, but you can expect it for end of January. There will not be a HotFix release.

**Pull request merged**
