### PR TITLE
Backporting fix for connecting to the wrong SQLServer host (#1965)

### PR DESCRIPTION
**Pull request by tkyc**
Backport of #1965

### CODE REVIEW

**Review by Jeffery-Wasty — APPROVED** [review]

**Review by lilgreenbird — APPROVED** [review]

**Comment by mmimica** [comment]
Hey. This commit somehow didn't make it to 11.2.2 https://github.com/microsoft/mssql-jdbc/blob/v11.2-servicing/src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java

**Comment by tkyc** [comment]
> Hey. This commit somehow didn't make it to 11.2.2 https://github.com/microsoft/mssql-jdbc/blob/v11.2-servicing/src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java

@mmimica, you're right. Apologies, this is our mistake. Do you need this fix in 11.2.2? This fix will be in the 12.2.2 GA coming in late January.

**Comment by mmimica** [comment]
I'm not going to use preview releases.
At least you should correct the 11.2.2 Changelog.

**Comment by tkyc** [comment]
The 12.2.0 is a GA. So it will be a stable release, not a preview. Again, apologies for the mistake.

**Pull request merged**
