### PR TITLE
Embed auth dll revert

### PR DESCRIPTION
**Pull request by tkyc**

### CODE REVIEW

**Review by lilgreenbird — APPROVED** [review]

**Review by Jeffery-Wasty — APPROVED** [review]

**Comment by cboehme** [comment]
Is there any information available why that feature was reverted? It looked really promising and I was hoping that it could  solve my problems with using integrated authentication in the liquibase-maven-plugin.

**Comment by tkyc** [comment]
@cboehme There are some licensing issues with embedding the DLL as it uses proprietary code.

**Comment by cboehme** [comment]
Thank you @tkyc, that's a pity. 
Wouldn't it be possible to distribute the DLL in a separate jar which uses the same license as the DLL? That way the DLL could still be loaded as a resource from the main driver jar but is not bundled with the MIT licensed driver code. Developers would then only have to include both jars in their applications to enable integrated authentication. This would save them fiddling with java.library.path.

**Comment by tkyc** [comment]
@cboehme Thanks for the suggestion. That would work, but I'll need to bring that up to management since it's their decision to make. We're still exploring solutions and nothing has been settled yet, but when we do I'll let you know. It might be awhile as right now this isn't a priority.

**Pull request merged**
