### PR TITLE
bulk mode insert with NULL GUID value (#1777)

### PR DESCRIPTION
**Pull request by andreitokar**
Fix for #1777

### CODE REVIEW

**Review by v-zhangw — APPROVED** [review]

**Review by Jeffery-Wasty — DISMISSED** [review]

**Review by tkyc — DISMISSED** [review]

**Review by lilgreenbird — APPROVED** [review]

**Review by lilgreenbird — CHANGES_REQUESTED** [review]
hi @andreitokar
thank you for the submission however could you please add a test for this?

**Comment by andreitokar** [comment]
@lilgreenbird,
The test would be a trivial addition of data to some CSV file, i.e. BulkCopyCSVTestInput.csv, but unfortunately existing testing framework does not support GUID type, and I do not fill comfortable to add such support due to a lack of knowledge about various aspects of SqlType sub-classing (coercions etc).

**Comment by v-zhangw** [comment]
Hi @andreitokar 
An easier way of adding this test would be to add it to BatchExecutionWithBulkCopy.java
Either as an addition to testNullOrEmptyColumns or as it's own test case.

**Comment by v-zhangw** [comment]
Something like 
`    @Test
    public void testNullGuid () throws Exception {
        String valid = "insert into " + AbstractSQLGenerator.escapeIdentifier(tableName) + " (c1) values (?)";
        try (Connection connection = PrepUtil.getConnection(connectionString + ";useBulkCopyForBatchInsert=true;");
                SQLServerPreparedStatement pstmt = (SQLServerPreparedStatement) connection.prepareStatement(valid);
                Statement stmt = (SQLServerStatement) connection.createStatement();) {
        pstmt.setNull(1, microsoft.sql.Types.GUID);
        pstmt.executeBatch();
        }
    }`

**Comment by andreitokar** [comment]
Thank you @v-zhangw . Of course, I could have done something like that, but just did not want to blow test code needlessly, since test for a dozen of other types is already in place, so I though, that the right way would be to include GUID support into the testing framework. But either way, it is a test.

**Review by Jeffery-Wasty — APPROVED** [review]

**Review by tkyc — APPROVED** [review]

**Review by tkyc — APPROVED** [review]

**Review by v-zhangw — APPROVED** [review]

**Pull request merged**
