### PR TITLE
Optimize imports

### PR DESCRIPTION
**Pull request by gstojsic**
This is in relation to **Wildcard in import statements (https://github.com/Microsoft/mssql-jdbc/issues/2)**. I used Intellij Idea's Optimize imports function to remove the wildcards. There are 4 files in the dev branch which I believe have been mistakenly committed with CRLF's instead of LF's so I corrected those too. These files are:
`KerbAuthentication.java`
`SQLServerConnectionPoolProxy.java`
`SQLServerDataSource.java`
`SQLServerPooledConnection.java`
I verified that these were committed with CRLF's by using:
`curl -o SQLServerConnectionPoolProxy.java -L https://github.com/Microsoft/mssql-jdbc/raw/dev/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionPoolProxy.java`
and then:
`hexdump -C SQLServerConnectionPoolProxy.java`
It is clearly visible that the hex dump contains 0d 0a sequences. Other files contain only 0a.

### CODE REVIEW

**Comment by v-xiangs** [comment]
@gstojsic hello thank you for fixing both import issue and CRLF issue.
I am wondering if you could split the PR into 2 different PRs, one for each issue. That would be much easier for us to test it and accept the PR. Thanks.

**Comment by gstojsic** [comment]
I'll do the CRLF issue first then.

**Comment by v-xiangs** [comment]
@gstojsic thank you for your understanding, can I go ahead and close this PR then?

**Comment by gstojsic** [comment]
sure

**Pull request closed without merging**
