### PR TITLE
JDK9 Compatibility + JDBC 4.3 API addition

### PR DESCRIPTION
**Pull request by cheenamalhotra**
This Pull Request:

* Makes the driver compatible to be compiled with **Java 9 JVM**. 
* Introduces **JDBC 4.3 APIs** added with Java 9.
* Builds **jre9** driver jars.
* Drops building _jre7_ jars.

### CODE REVIEW

**Comment by NersesAM** [comment]
Any chance you will do a new release soon? It will be great to have Java 9 compatibility released soon as without it, it is not possible to upgrade apps to 9

**Comment by cheenamalhotra** [comment]
Hi @NersesAM 
Yes, we are proceeding to release soon. Stay tuned!

**Comment by NersesAM** [comment]
great! thanks @cheenamalhotra

**Comment by NersesAM** [comment]
hi @cheenamalhotra 
The README says 6.4.0.jre9 can be used but it's not available in maven central. That was merged 11 days ago? When do you think you will be able to release it to maven central?

**Comment by cheenamalhotra** [comment]
Hi @NersesAM 
It will be available on Maven Central in next few hours.. we have published the artifacts on Maven :)

The release artifacts are also available in Download Center [here](https://www.microsoft.com/en-us/download/details.aspx?id=56615).

**Comment by NersesAM** [comment]
great! thank you @cheenamalhotra 
tomorrow i can finally upgrade to java 9!

**Pull request merged**
