### PR TITLE
Test case for a select statement with prepared statement with parameters

### LINKED ISSUE #443: PreparedStatement.setTimestamp(index, timestamp, calendar) has datatype conversion issues.
## Driver version or jar name
The test works correctly with the old version of driver (2.0.1803), but fails with 4.x and 6.x, including 6.2.1 and 6.3 preview.

## SQL Server version
Microsoft SQL Server 2008 (SP4) - 10.0.6241.0 (X64) 

## Client operating system
Windows 7

## Java/JVM version
Oracle JDK 1.8.0_xxx

## Table schema
See the test code [Stand alone test class](https://github.com/goldmansachs/reladomo/blob/master/reladomo/src/test/java/com/gs/fw/common/mithra/test/vendor/SetTimestampWithUtc.java)

## Problem description
See the test code here: [Stand alone test class](https://github.com/goldmansachs/reladomo/blob/master/reladomo/src/test/java/com/gs/fw/common/mithra/test/vendor/SetTimestampWithUtc.java)

## Expected behavior and actual behavior
When the query is executed with a prepared statement, it should return the correct result.

## Repro code
[Stand alone test class](https://github.com/goldmansachs/reladomo/blob/master/reladomo/src/test/java/com/gs/fw/common/mithra/test/vendor/SetTimestampWithUtc.java)
This test code works correctly with MSSQL/2.0 driver, MSSQL/jtds driver, 4 other commercial and 3 open source databases. It fails with 4.x and 6.x series drivers.

### PR DESCRIPTION
**Pull request by gs-rezaem**
See #443 for background. 
This is a non-failing test case that tests PreparedStatement.setTimestamp.
To fix #443, the data will be changed to .999 (from .003).

### CODE REVIEW

**Comment by gs-rezaem** [comment]
Looking at the failure.

**Comment by gs-rezaem** [comment]
I need a little help here. The test passes locally. I thought it has to do with timezones, so I did everything as UTC, but it doesn't seem to help.

**Comment by peterbae** [comment]
Hi @gs-rezaem. I tried out the test locally, and it failed for me too - until I changed the col1 to col2 on line 70. I believe this error is caused by the issue we're trying to fix (the rounding error), and it's passing for you locally because you have the fix already (it fails for me, so that's what I imagine).

Please let me know if you run into anything else. Thanks for your contribution 👍

**Comment by gs-rezaem** [comment]
So I changed it to 000 and it passes here. I'd chosen 003 because it doesn't have a rounding issue (the db can store 003 as a datetime). That's quite concerning, because the only difference I can think of is that I'm on an old version of SQL Server (10), so this problem may have become worse?

**Comment by gs-rezaem** [comment]
Work in progress... looking at the tests

**Comment by gs-rezaem** [comment]
need a little help here. I'm trying to run the encrypted tests and I'm getting this error:
```
org.opentest4j.TestAbortedException: Assumption failed: Aborting test case since no java key store and alias name exists!

	at org.junit.jupiter.api.Assumptions.throwTestAbortedException(Assumptions.java:246)
	at org.junit.jupiter.api.Assumptions.assumeTrue(Assumptions.java:119)
	at org.junit.jupiter.api.Assumptions.assumeTrue(Assumptions.java:104)
	at com.microsoft.sqlserver.jdbc.AlwaysEncrypted.AESetup.readFromFile(AESetup.java:147)
	at com.microsoft.sqlserver.jdbc.AlwaysEncrypted.AESetup.setUpConnection(AESetup.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
```

**Comment by v-afrafi** [comment]
Hi @gs-rezaem . You need to create the certificates in order to be able to run the Always Encrypted tests. [This wiki](https://github.com/Microsoft/mssql-jdbc/wiki/How-to-run-Always-Encrypted-tests-locally) page will guide you in setting up the environment.  Thanks.

**Comment by peterbae** [comment]
Hi @gs-rezaem, I hope you are doing well. Do you have any updates on this issue?

**Comment by gs-rezaem** [comment]
This is a fix for #443, which can't be fixed until #493 is fixed. I'm not touching #493, so this will have to stay unfixed until someone fixes #493.

**Comment by peterbae** [comment]
Hi @gs-rezaem, issue #493 has been fixed, so we can work on this issue again. However, the PR's been open for a while and there's some conflicts. Would you like to resolve these yourself, or would you like for me to take over this PR and continue where you left off? Thanks.

**Comment by gs-rezaem** [comment]
@peterbae As I no longer have easy access to MS SQL, please go ahead and take over. Thanks.

**Comment by Jeffery-Wasty** [comment]
Hi @gs-rezaem,

Thank you again for the test case. With #1687, the issue you originally were seeing can be avoided using the `datetimeParameterType` set to `dateTime`. Please let us know if this solution (available in 12.2+ works for you). If not, we can take another look at the "legacyDateTime" option you have here and whether its something we can incorporate. Closing, but will reopen if necessary.

**Pull request closed without merging**
