### PR TITLE
Allow using multiple JAAS configurations and override the configuration per connection properties

### PR DESCRIPTION
**Pull request by pierresouchay**
We also set a different default LoginConfig for IBM JVM, so it should work well with user-provided
passwords and username for Kerberos.

Should solve https://github.com/Microsoft/mssql-jdbc/issues/66 for IBM JVM.

### CODE REVIEW

**Comment by v-suhame** [comment]
Thanks @pierresouchay! Commits that were already in the dev branch got added to this PR when I submitted few changes. Can you rebase the code? I for some reason don't have permission.

**Comment by pierresouchay** [comment]
@v-suhame DONE

**Comment by v-suhame** [comment]
Perfect! Thanks for contributing @pierresouchay!

**Comment by pierresouchay** [comment]
@v-suhame cool!

Does it solves https://github.com/Microsoft/mssql-jdbc/issues/66 with IBM JVM?

**Comment by v-suhame** [comment]
Yes, it did solve #66 :)

**Pull request merged**
