### PR TITLE
Query with timer can throw IllegalThreadStateException

### PR DESCRIPTION
**Pull request by maiken2051**
Running a query that uses a timer can cause an IllegalThreadStateException if the underlying ThreadGroup has been destroyed.

This error happens when the caller executes a query with a timeout and then doesn't execute another query with a timeout until some time has elapsed. The JVM can destroy the ThreadGroup behind the TimeoutTimer (because it contains no active threads) which causes any new query with a timeout to throw an IllegalThreadStateException.

Once the JDBC driver has entered this state any new query with a timeout will throw the exception. It's especially easy to run into this problem in demanding / multi-threaded applications.

My change makes sure the ThreadGroup is not destroyed before creating a new timer thread. If the ThreadGroup is destroyed, the code will create a new ThreadGroup.

### CODE REVIEW

**Comment by v-afrafi** [comment]
@maiken2051 Thank you for your effort in creating this pr. Could you please open this to dev branch?

**Comment by ajlam** [comment]
Hi @maiken2051, would you be able to reopen this PR against the dev branch?

**Comment by maiken2051** [comment]
Thanks for rebasing the PR...

**Comment by ajlam** [comment]
@maiken2051, just wanted to keep you posted. We are going to be doing a code review soon. Thanks again for your contributions.

**Comment by cheenamalhotra** [comment]
Hi @maiken2051 Please sign CLA so that we can proceed with merging your PR.

**Comment by maiken2051** [comment]
I think the CLA should be OK now?

**Comment by peterbae** [comment]
Hi @maiken2051, thanks for the contribution. The changes look good, and I approved it - but I'm curious as to where I can find the information regarding JVM destroying a ThreadGroup that contains no active threads. Could you point me to where I can read more about this?

**Comment by maiken2051** [comment]
Check out the source for [ThreadGroup.threadTerminated](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/lang/ThreadGroup.java#ThreadGroup.threadTerminated%28java.lang.Thread%29). This is from OpenJDK but I assume all JVM implementations are similar. The docs say:

> Notifies the group that the thread t has terminated. Destroy the group if all of the following conditions are true: this is a daemon thread group; there are no more alive or unstarted threads in the group; there are no subgroups in this thread group.

When a thread exits it will call this method to remove itself from the active list on its owner ThreadGroup. If it's the last active thread the group will be destroyed.

**Pull request merged**
